version: '3.9'

services:
  back:
    container_name: name-rest
    build: .
    ports:
      - 8008:8000
    volumes:
      - .:/app
      - /app/.venv
    command: uvicorn src.main:app --host 0.0.0.0

  db:
    container_name: name-db
    image: "cassandra:latest"  # cassandra:4.1.3
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      - CASSANDRA_USER=superadmin
      - CASSANDRA_PASSWORD=superadmin
    volumes:
      - name-data:/var/lib/cassandra:rw
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

volumes:
  name-data:
